// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAdebTl3BVg09jN9Mm2jS_TxJa7V6cc4',
    appId: '1:262634425294:web:f7023897dfae7df85fb99f',
    messagingSenderId: '262634425294',
    projectId: 'oyo-clone-73273',
    authDomain: 'oyo-clone-73273.firebaseapp.com',
    storageBucket: 'oyo-clone-73273.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCszOcBoaPlp_4p58uqFsl2XIW5CaICtVo',
    appId: '1:262634425294:android:b984e00d31ed45645fb99f',
    messagingSenderId: '262634425294',
    projectId: 'oyo-clone-73273',
    storageBucket: 'oyo-clone-73273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJQQ_vfh1U5Dhigv-YHUvBeH-eL3Y9vE',
    appId: '1:262634425294:ios:f260b231a74ecfc65fb99f',
    messagingSenderId: '262634425294',
    projectId: 'oyo-clone-73273',
    storageBucket: 'oyo-clone-73273.appspot.com',
    iosBundleId: 'com.example.abhishekApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJQQ_vfh1U5Dhigv-YHUvBeH-eL3Y9vE',
    appId: '1:262634425294:ios:eb882e97b2bf13915fb99f',
    messagingSenderId: '262634425294',
    projectId: 'oyo-clone-73273',
    storageBucket: 'oyo-clone-73273.appspot.com',
    iosBundleId: 'com.example.abhishekApplication.RunnerTests',
  );
}
